language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install: make install
script: make test
addons:
  sauce_connect: true
env:
  global:
  - secure: acuOAssIorJ+zegbgbw/S3rc/yoHdUeM63Uiq7cfCi2a8eP8HVjwGbmAYaDEs8i3BnYMc5lk/RzRoOCqHbKjhyEdOZRIc+hPqpo8+6JfZM6lM2FwC18RkDRAE/j1c6wRM9pDiwkbXA/kdOyRTncK0rY3QnpTk5JS+rVVTx7RJFg=
  - secure: ePMYH6BboRrtLiJMz0dOx9rKrW0geA+x3JFzS1aRKE84xXGDQHvJQw6iEBCDDHOGKbq8whDpw3KN8g4naztLfCwH3ec217RTfVODoD/hWLxJUe7tqj3qxVFiwooJqgXBASXANweFRCaQeZoD3aHzN5DBbLulH4uHhmBy36uYLL8=
  - secure: J0F5Uhcil7OD7qj0i3v94VU85QI7bz8j30GUq04pD5E6zgJDL9k0rQXhskZVePKPXmDc1dAAW6bMCJNjVSRPabEp+CYtUmkCg/cxzpxZl28y8mF2/rJb/Cu4LNCVrwgA2I9baTIWAYeeV0ES9zMekGSPpI7NFlD3RCnqWYtKdhY=
